name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_builds:
    name: Run All Tests
    if: github.repository == 'cwcontur/Contursi-Marlin-Firmware'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-platform:
        # Base Environments

        - DUE
        - DUE_archim
        - esp32
        - linux_native
        - mega2560
        - at90usb1286_dfu
        - teensy31
        - teensy35
        - teensy41
        - SAMD51_grandcentral_m4

        # Extended AVR Environments

        - FYSETC_F6
        - mega1280
        - rambo
        - sanguino1284p
        - sanguino644p

        # STM32F1 (Maple) Environments

        #- STM32F103RC_btt_maple
        - STM32F103RC_btt_USB_maple
        - STM32F103RC_fysetc_maple
        - STM32F103RC_meeb
        - jgaurora_a5s_a1_maple
        - STM32F103VE_longer_maple
        #- mks_robin_maple
        - mks_robin_lite_maple
        - mks_robin_pro_maple
        #- mks_robin_nano35_maple
        #- STM32F103RET6_creality_maple
        - STM32F103VE_ZM3E4V2_USB_maple

        # STM32 (ST) Environments

        - STM32F103RC_btt
        #- STM32F103RC_btt_USB
        - STM32F103RE_btt
        - STM32F103RE_btt_USB
        - STM32F103RET6_creality
        - STM32F103VE_longer
        - STM32F407VE_black
        - STM32F401VE_STEVAL
        - BIGTREE_BTT002
        - BIGTREE_SKR_PRO
        - BIGTREE_GTR_V1_0
        - mks_robin
        - ARMED
        - FYSETC_S6
        - STM32F070CB_malyan
        - STM32F070RB_malyan
        - malyan_M300
        - FLYF407ZG
        - rumba32
        - LERDGEX
        - LERDGEK
        - mks_robin_nano35
        - NUCLEO_F767ZI
        - REMRAM_V1
        - BTT_SKR_SE_BX
        - chitu_f103

        # Put lengthy tests last

        - LPC1768
        - LPC1769

        # Non-working environment tests
        #- at90usb1286_cdc
        #- STM32F103CB_malyan
        #- STM32F103RE
        #- mks_robin_mini

    steps:

    - name: Install PlatformIO
      run: |
        pip install -U https://github.com/platformio/platformio-core/archive/develop.zip
        platformio update

    - name: Run ${{ matrix.test-platform }} Tests
      run: |
        make tests-single-ci TEST_TARGET=${{ matrix.test-platform }}
